[package]
name = "tokio-lk"
version = "0.1.0"
authors = ["zenix <zenixls2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1.22"
futures = "0.1.29"
lazy_static = "1.4.0"

[dev-dependencies]
crossbeam = "0.7.3"
